version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/dhaka
    overwrite: true

permissions:
  - object: /var/www/dhaka
    pattern: "**"
    owner: apache
    group: apache
    mode: 775
    type:
      - directory
      - file

hooks:
  BeforeInstall:

  AfterInstall:

  ApplicationStop:
